server:
  port: 8083

spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

app:
  sqs:
    card-issuance-queue: card-issuance-queue
  cache:
    product-ttl-minutes: 30
  clients:
    product-service:
      base-url: http://localhost:8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
